### ISSUE TITLE
"from_selection_table_map" error

### ISSUE THREAD

**Issue by AliOzFal** [shyamblast/Koogu#2]
Hi, 

When running "from_selection_table_map" I am recieving the error: 

> "return tuple([SelectionTableReader._convert(entry[c_spec[0]], c_spec[1], c_spec[2])
>  IndexError: list index out of range"

I belive this is caused by the tuple "entry" which is created when I run "from_selection_table_map". In my case, index [2] contains a NoneType object: 

> 16, 3465.293099146, None

I was wondering what the input for "entry" is so I can discern what might be causing this. I haven't been able to find this information in the Koogu documentation. 

Thanks!

**Comment by shyamblast** [comment]
This error is usually caused due to a missing or empty field value in the selection table. In this case, I think it's one or more rows missing values in the labels/tags column.
Could you check your selection table file(s) and make sure that all rows have non-empty values in the `Begin Time (s)`, `End Time (s)` and `Tags` (or whatever your labels column is named) columns.

**Comment by AliOzFal** [comment]
Thanks for getting back to me.  

This would make sense, my annotation column specified in "label_column_name" contains many blank entries. Is there a way to select for blank entries using "desired_labels"?

**Comment by shyamblast** [comment]
@AliOzFal , the "meaning" of blank fields could be interpreted differently in different projects; but for all practical purposes, the onus should be on making sure that the training dataset is clean. Hence, I had made the decision to not assume any meaning, but to let the program complain. `desired_labels` only lets you pick and limit model's classes when the class labels are proper strings; it's not an interface to deal with None type.
Hope that answers your question. If satisfied, please close the issue.
Also, the upcoming release will have better error reporting on the issue of malformed selection table files. Stay tuned!

**Comment by AliOzFal** [comment]
Thanks for the response, this satisfies my query.
