### ISSUE TITLE
Initialize Data Feeder Errors

### ISSUE THREAD

**Issue by srfreeze** [shyamblast/Koogu#4]
Hello. I get the following errors when I try to initialize the data feeder for training. I am not familiar with python programming, so any help would be much appreciated! Thanks!

# Set up a feeder that
#   i)   loads the pre-processed audio clips,
#   ii)  transforms the waveform clips into spectrograms, and
#   iii) feeds them into the training pipeline.

data_feeder = feeder.SpectralDataFeeder(
    prepared_audio_dir,                               #where the prepared clips are at
    data_settings['audio_settings']['desired_fs'],
    data_settings['spec_settings'],
    validation_split=0.01,                             #set aside xx% for validation
    max_clips_per_class=1500                          #use up to x inputs per class
)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-6-d5695b45286d>](https://localhost:8080/#) in <cell line: 6>()
      4 #   iii) feeds them into the training pipeline.
      5 
----> 6 data_feeder = feeder.SpectralDataFeeder(
      7     prepared_audio_dir,                               #where the prepared clips are at
      8     data_settings['audio_settings']['desired_fs'],

2 frames
[/usr/local/lib/python3.9/dist-packages/koogu/data/feeder.py](https://localhost:8080/#) in build_dataset_info(data_dir, num_classes, validation_split, random_state, min_clips_per_class, max_clips_per_class, suppress_nonmax)
    434             for file in recursive_listing(
    435                 data_dir, match_extensions=FilenameExtensions.numpy)]
--> 436         assert num_classes == per_file_class_counts[0].shape[0]
    437 
    438         class_files_tr, class_files_ev = [], []

IndexError: list index out of range

**Comment by shyamblast** [comment]
I tried decoding your message, but I cannot make sense of the message, or of the error you wanted to describe without any context. If the previous steps were executed correctly (and if they had produced any outputs), the Feeder **does** work as expected.

Also, please note that this is not a forum for seeking help with Python or regarding understanding on ML.
