### ISSUE TITLE
Customization of loss function

### ISSUE THREAD

**Issue by C1587S** [shyamblast/Koogu#5]
Hello,

I'm trying to train a multiclass model. However, exploring the tutorials and source code, I can only find routines to train binary class models. Is there an easy way to train multiclass models? Say, for example, changing from `binary_accuracy` to `categorical_accuracy`?

**Comment by shyamblast** [comment]
Hi!

The boolean parameter `multilabel` (in model constructor) dictates whether the model will be a single-label (categorical accuracy/loss, with soft-max activation on leaf-nodes) or multi-label (binary accuracy/loss, with sigmoid activation on leaf-nodes). By default, it is set to True, meaning models will be multi-label.

This parameter can be specified in the constructors of the available architectures (convnet & densenet).
If you're extending `model.architectures.BaseArchitecture` to implement your own architecture (including transfer learning models), be sure to set the `multilabel` parameter when you invoke the base class constructor.
