### ISSUE TITLE
Possible bug (or user error) with data feeder

### ISSUE THREAD

**Issue by dsbennett2023** [shyamblast/Koogu#8]
Good evening, hope it is OK if I post here. 

Ive been trying to use your package to build a classifier, and it was gong well until I encountered an error - specifically when trying to prepare the data feeder. 

Using the following audio settings (although have experimented with altering them to see if it could be causing the problem, no luck)

audio_settings = {
  'clip_length': 2.0,           # in seconds
  'clip_advance': 0.5,          # in seconds
  'desired_fs': 250000           # in Hz
}

# Path to the directory where processed/prepared audio will be written
#prepared_audio_dir = '/mnt/projects/dolphins/prepared_clips'
prepared_audio_dir = '/content/drive/My Drive/SoundscapeProto3/Prepared'

spec_settings = {
  'win_len': 0.008,                 # in seconds
  'win_overlap_prc': 0.50,          # as a fraction
  'bandwidth_clip': [1, 250000],  # in Hz
  #'num_mels': 60                   # Uncomment to enable mel-scale conversion
}

and finally, 

data_feeder = feeder.SpectralDataFeeder(
  prepared_audio_dir,
  audio_settings['desired_fs'],
  spec_settings,
  validation_split=0.15)

It is at this step where I get the problem: it tells me I have index errors:
"IndexError                                Traceback (most recent call last)
[<ipython-input-91-c046dd05d145>](https://localhost:8080/#) in <cell line: 1>()
----> 1 data_feeder = feeder.SpectralDataFeeder(
      2   prepared_audio_dir,
      3   audio_settings['desired_fs'],
      4   spec_settings,
      5   validation_split=0.15)

2 frames
[/usr/local/lib/python3.10/dist-packages/koogu/data/feeder.py](https://localhost:8080/#) in build_dataset_info(data_dir, num_classes, validation_split, random_state, min_clips_per_class, max_clips_per_class, suppress_nonmax)
    434             for file in recursive_listing(
    435                 data_dir, match_extensions=FilenameExtensions.numpy)]
--> 436         assert num_classes == per_file_class_counts[0].shape[0]
    437 
    438         class_files_tr, class_files_ev = [], []

IndexError: list index out of range"

What I do not understand here, is that it imples the issue is with the class counts. However, none of my classes have zero entries.

Is this a bug, or am I just being stupid?

I would be eternally grateful for any assistance in this. Have attached a zip of some of my data and the script going into the error. 

[SoundscapeProto3.zip](https://github.com/shyamblast/Koogu/files/13059321/SoundscapeProto3.zip)

**Comment by shyamblast** [comment]
Hi David.

Thanks for sharing your code and data. That helped identify the issue quickly.

When you build your `audio_annot_list`, you are specifying absolute paths. As a result, the intermediate files are getting written to the "source" directories (you'll see in your WavFiles folder, there'll be as many .npz files as there were .wav files) instead of being written to where `prepared_audio_dir` points to. Subsequently, the feeder complains because it couldn't find any intermediate files where it was supposed to.

If you change the line where you build the list of pairs, to simply include relative paths (relative to `audio_root` and `annots_root`), as:
`audio_annot_list = [[wav, txt] for wav, txt in zip(wav_files, txt_files)]`
that should fix your problem.

**Comment by dsbennett2023** [comment]
That worked perfectly, thank you so much!!

Ive now succesfully built a CNN, however when I run it on an input folder of new files I only get an (almost) blank text output. I selected these files a prototype - there a dozen, which I know have a given species.

Is it a bug? Or does it imply that the model is just very weak so far and cannot detect anything?

**Comment by shyamblast** [comment]
That depends on a lot of things: data quality & quantity, model params, training params, etc.
However, this isn't the place to address such questions.
